# Generated by Django 5.2.1 on 2025-06-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(),
        ),
    ]
